/**
 * Mock Data Helpers for Tests
 * Provides factory functions to create test data
 */

import type {
  Recommendation,
  UserSignals,
  DecisionTrace,
  OperatorStats,
  Alert,
} from "@/lib/types";

/**
 * Create a mock recommendation
 */
export function createMockRecommendation(
  overrides?: Partial<Recommendation>
): Recommendation {
  return {
    id: "rec_test_001",
    user_id: "user_test_123",
    persona_primary: "high_utilization",
    type: "educational",
    title: "Understanding Credit Utilization",
    rationale:
      "Based on high credit card utilization patterns, this educational content will help.",
    priority: "high",
    status: "pending",
    generated_at: "2025-11-05T10:00:00Z",
    content_url: "https://example.com/article/credit-utilization",
    read_time_minutes: 5,
    guardrails_passed: {
      tone_check: true,
      advice_check: true,
      eligibility_check: true,
    },
    ...overrides,
  };
}

/**
 * Create multiple mock recommendations
 */
export function createMockRecommendations(
  count: number,
  overrides?: Partial<Recommendation>
): Recommendation[] {
  return Array.from({ length: count }, (_, index) =>
    createMockRecommendation({
      id: `rec_test_${String(index + 1).padStart(3, "0")}`,
      ...overrides,
    })
  );
}

/**
 * Create mock user signals
 */
export function createMockUserSignals(
  overrides?: Partial<UserSignals>
): UserSignals {
  return {
    user_id: "user_test_123",
    persona_30d: {
      primary: "high_utilization",
      secondary: "subscription_heavy",
      match_strength: 0.85,
    },
    signals: {
      credit: {
        aggregate_utilization_pct: 75,
        total_credit_used: 7500,
        total_credit_available: 10000,
        any_interest_charges: true,
      },
      subscriptions: {
        recurring_merchant_count: 8,
        monthly_recurring_spend: 250,
        subscription_share_pct: 15,
        merchants: [
          { name: "Netflix", amount: 15.99 },
          { name: "Spotify", amount: 10.99 },
        ],
      },
      savings: {
        total_savings_balance: 5000,
        savings_growth_rate_pct: 5,
        net_savings_inflow: 200,
        emergency_fund_months: 3,
      },
      income: {
        income_type: "salaried",
        payment_frequency: "biweekly",
        median_pay_gap_days: 14,
        income_variability_pct: 5,
        cash_flow_buffer_months: 2,
      },
    },
    ...overrides,
  };
}

/**
 * Create mock decision trace
 */
export function createMockDecisionTrace(
  overrides?: Partial<DecisionTrace>
): DecisionTrace {
  const now = new Date().toISOString();

  return {
    recommendation_id: "rec_test_001",
    signals_detected_at: now,
    persona_assigned_at: now,
    content_matched_at: now,
    rationale_generated_at: now,
    guardrails_checked_at: now,
    created_at: now,
    signals: createMockUserSignals().signals,
    persona_assignment: {
      primary_persona: "high_utilization",
      primary_match_strength: 0.85,
      criteria_met: ["credit_utilization_above_threshold", "interest_charges"],
    },
    content_matches: [],
    relevance_scores: [],
    rationale: "Test rationale generated by LLM",
    llm_model: "gpt-4",
    temperature: 0.7,
    tokens_used: 150,
    tone_check: true,
    advice_check: true,
    eligibility_check: true,
    guardrails_passed: true,
    priority: "high",
    type: "educational",
    ...overrides,
  };
}

/**
 * Create mock operator stats
 */
export function createMockOperatorStats(
  overrides?: Partial<OperatorStats>
): OperatorStats {
  return {
    pending: 15,
    approved_today: 8,
    rejected_today: 2,
    flagged: 1,
    avg_review_time_seconds: 45,
    ...overrides,
  };
}

/**
 * Create mock alert
 */
export function createMockAlert(overrides?: Partial<Alert>): Alert {
  return {
    id: "alert_test_001",
    type: "high_rejection_rate",
    severity: "medium",
    message: "Rejection rate above normal (25% vs avg 15%)",
    count: 5,
    actionUrl: "/audit-logs",
    createdAt: new Date().toISOString(),
    ...overrides,
  };
}

/**
 * Create multiple mock alerts
 */
export function createMockAlerts(count: number): Alert[] {
  const alertTypes: Alert["type"][] = [
    "high_rejection_rate",
    "long_queue",
    "guardrail_failures",
    "llm_errors",
    "flagged_item",
  ];

  return Array.from({ length: count }, (_, index) =>
    createMockAlert({
      id: `alert_test_${String(index + 1).padStart(3, "0")}`,
      type: alertTypes[index % alertTypes.length],
    })
  );
}
